name: test_install
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  test_install:
    runs-on: ubuntu-latest
    env:
      TERM: "linux"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: 'pip'
      - run: pip install --upgrade pip
      - run: pwd && ls -hal
      # How can we pipe in responses to `read` prompts?
      #-  run: echo -e "\n1\n1\n1\n" | sudo ./install.sh
      - run: sudo ./install.sh 1
      - run: pwd && ls -hal
      - run: echo -e "1\n/home/runner/work/hackingtool/hackingtool\n" | hackingtool || true
      - run: pwd && ls -hal

