name: test_install
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  test_install:
    runs-on: ubuntu-latest
    env:
      TERM: "linux"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: 'pip'
      - run: pip install --upgrade pip
      - run: pwd && ls -hal
      - run: sudo ./install.sh 1
      - run: pwd && ls -hal
      # Typing "1" will allow us to manually enter a path.
      # Provide a path to a writable directory: /home/runner/work/hackingtool/hackingtool
      # Typing "99" will quit hackingtool. 
      - run: echo -e "1\n/home/runner/work/hackingtool/hackingtool\n99\n" | hackingtool
      - run: pwd && ls -hal

